name: Lizard Runner
on:
  schedule:
    # At 00:00 on Monday (JST)
    - cron: '0 15 * * SUN'

jobs:
  lizard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lizard Runner
        uses: Uno-Takashi/Lizard-Runner@v3
        with:
          path: "./src/common ./src/scraping ./src/deepLearning"
          CCN: "20"
          